### ISSUE TITLE
Could this add to the IOS shortcuts?

### ISSUE THREAD

**Issue by TTTiger2020** [antongaenko/keybro#7]
For IOS shotcuts(https://support.apple.com/guide/shortcuts) provide many convenient way to control the ipad/iphone.If the keyboard input option could be added to them, we genral users who aren't developer could use the founction to do many thing.Thanks~

**Comment by antongaenko** [comment]
hi @TTTiger2020, I'm not sure I got a whole idea. Can you describe your idea in more details, may be with some examples? Actually the main purpose of this lib is to add debug shortcuts to speed up development and testing for developers. 

Thanks

**Comment by TTTiger2020** [comment]
Sorry for being not skilled in English. I want to have a option in the app — shortcuts, which is equaled to typing one key in the keyboard, for example :just type the letter “i” in the keyboard.So I find it in the apple support in shortcuts but failed. Then I saw your project which seems like the solution, but as you said ,the project seems aiming to programming, is there anyway to link it to directly using in the shortcuts?XD

**Comment by antongaenko** [comment]
oh I see now, unfortunately it's only for adding keyboard shortcuts for developing benefits not "Shortcuts" :) @TTTiger2020

**Comment by TTTiger2020** [comment]
@antongaenko Oh I see, I confused them. XD . Thank you very much lol.
